Feature/docs 0 2 0
databrickslabs/mosaic pull request #181
Opened 2022-07-28 15:49 UTC by edurdevic

I added the Kepler docs and updated the version of the docs

2022-07-29 09:16 UTC, edurdevic commented
Changes:

- Reordered the function names alphabetically in the docs and in the MosaicContext
- Separated the indexing functions from the spatial functions
- Added some more elaborate description of the indexing functions
- Corrected a few inconsistencies in the docs
- Updated the docs version
- Added Kepler docs

2022-07-29 13:08 UTC, milos-colic requested changes
Can we please add missing authors.
And can we please change usage of column with col and $ with col.
This will ensure python and scala code is more similar to one another.
No real benefit in not using col in both.

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-functions.rst
> +    >>> showDF(select(df, st_ymax(column("wkt"))), truncate=F)
col instead of column

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-functions.rst
> +    >>> df.select(st_ymin($"wkt")).show()
col instead of $

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-functions.rst
> +    >>> showDF(select(df, st_ymin(column("wkt"))), truncate=F)
col instead of column

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> df.select(mosaic_explode($"wkt", lit(0))).show()
col instead of $

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> df.select(mosaicfill($"wkt", lit(0))).printSchema
col instead of $

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> schema(select(df, mosaicfill(column("wkt"), lit(0L))))
col instead of column

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> showDF(select(df, mosaicfill(column("wkt"), lit(0L))))
col instead of column

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> df.select(point_index_geom(st_point($"lon", $"lat"), lit(10))).show()
col instead of $

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> showDF(select(df, point_index_geom(st_point(column("lon"), column("lat")), lit(10L))), truncate=F)
col instead of column

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> df.select(point_index_lonlat($"lon", $"lat", lit(10))).show()
col instead of $

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> showDF(select(df, point_index_lonlat(column("lon"), column("lat"), lit(10L))), truncate=F)
col instead of column

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> df.select(polyfill($"wkt", lit(0))).show(false)
col instead of $

2022-07-29 13:08 UTC, milos-colic commented on docs/source/api/spatial-indexing.rst
> +    >>> showDF(select(df, polyfill(column("wkt"), lit(0L))), truncate=F)
col instead of column

2022-07-29 13:08 UTC, milos-colic commented on docs/source/conf.py
>  author = 'Stuart Lynn, Milos Colic'
add @edurdevic, @robertwhiffin, @tiems90 
we should add authorship to all contributors with solutions and code contribution.

2022-07-29 14:48 UTC, edurdevic commented on docs/code-example-notebooks/kepler.py
> +# MAGIC 1) `dataset`: Can be a Spark dataset or a string representing a table/view name
I tested it and it does not work with native types and WKB. So I preferred not to advertise it for now

2022-07-29 14:50 UTC, edurdevic commented on docs/code-example-notebooks/kepler.py
> +# MAGIC 2) `column_name`: The column that needs to be plotted, can be either a geometry column (`WKT`, `WKB` or Mosaic internal format) or a column containing a spatial grid index ID
It would have to be a json object, because the JSON string won't work (will think it is WKT).
I prefer not to mention it for simplicity.

2022-07-29 14:54 UTC, edurdevic commented on docs/code-example-notebooks/kepler.py
> +    .select("type", col("feature.properties").alias("properties"), to_json(col("feature.geometry")).alias("geom_json"))
No, the to_json is a native Spark function.
The fix was on the mosaic conversion methods.

2022-07-29 14:56 UTC, edurdevic commented on docs/source/api/spatial-functions.rst
> +    >>> df.select(flatten_polygons($"wkt")).show(false)
Ok

2022-07-29 14:56 UTC, edurdevic commented on docs/source/api/spatial-functions.rst
> +    >>> showDF(select(df, flatten_polygons(column("wkt"))), truncate=F)
Will col work in R? I never tried that.

2022-07-29 15:44 UTC, edurdevic commented on docs/source/api/spatial-functions.rst
> +    >>> showDF(select(df, flatten_polygons(column("wkt"))), truncate=F)
I tried it and it does not work. R needs `column`.

2022-07-29 15:47 UTC, edurdevic commented
@milos-colic I added the missing authors and refactored $"" in col.
It is not possible to refactor column to col for R code.

2022-08-02 13:26 UTC, milos-colic commented on docs/source/api/spatial-functions.rst
> +    >>> showDF(select(df, st_distance(column("poly"), column("point"))))
@edurdevic can we please use col in both python and scala. "column" makes it look like the syntax is different between the two for no benefits

2022-08-02 13:27 UTC, milos-colic requested changes
Can we replace "column(...)" with "col(...)" so the docs have same syntax in all languages where that is possible.

2022-08-03 12:59 UTC, milos-colic approved these changes

2022-08-03 12:59 UTC, merged